"""crear tabla parametros_config

Revision ID: f469bf3fe3ec
Revises: 6aabcd312ed2
Create Date: 2026-09-14 23:19:23.168583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f469bf3fe3ec'
down_revision: Union[str, Sequence[str], None] = '6aabcd312ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parametros_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('voltaje_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('voltaje_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('thd_max', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('corriente_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('factor_potencia_min', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('frecuencia_nominal', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipo_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parametros_config')
    # ### end Alembic commands ###
